### ISSUE TITLE
reactiveの使い方が惜しい

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pon0204/svelte-counter#12]
https://github.com/pon0204/svelte-counter/blob/a0d312adfd9e85332990baf2e126c02280855369/src/App.svelte#L20-L24

**Comment by KoichiKiyokawa** [comment]
```ts
$: countSum = ...
$: titleList = ...
```
のように使うのが一般的です。すべてを混ぜてしまうと、余計な再計算が走りやすくなってしまいます。

**Comment by KoichiKiyokawa** [comment]
また、titleListはArray.prototype.joinを使うともう少しスマートに書けると思います

**Comment by pon0204** [comment]
@KoichiKiyokawa 

https://github.com/pon0204/svelte-counter/issues/2
> すみません、PRって基本的に作った本人はマージしない想定でした 🙇
PRとissueを紐付けて、PRがマージされるとissueが自動でcloseされるというのがよくあるパターンだと思います

失礼しました🙇‍♂️

- https://docs.github.com/ja/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue
- https://qiita.com/kodai_0122/items/18f7faa80f0302244c51

以上のサイトを参考に紐付けてみましたが、出来ていますでしょうか?
