### ISSUE TITLE
カウンターの値がマイナスになる

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pon0204/svelte-counter#2]
仕様の伝え漏れかもしれません 🙇 
マイナスの値をカウントしたいという要望もありそうなのですが、基本的に0未満にはならないほうが良いかもしれません 🙆‍♂️

**Comment by pon0204** [comment]
@KoichiKiyokawa 
普通そうですよね。。。完全に抜けてました🙇‍♂️ 

【プルリクエストリンク】
https://github.com/pon0204/svelte-counter/pull/9

ご確認宜しくお願い致します。

**Comment by KoichiKiyokawa** [comment]
すみません、PRって基本的に作った本人はマージしない想定でした 🙇 
PRとissueを紐付けて、PRがマージされるとissueが自動でcloseされるというのがよくあるパターンだと思います
