### ISSUE TITLE
型定義のファイル名、変数名

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pon0204/svelte-counter#3]
`types/types.ts`というのは冗長なので、
- ルートディレクトリに`types.ts`
or
- `types/index.ts`

のいずれかが良いかもです。

また、`CounterType`というのも少しだけ冗長なので、`ICounter`(頭にinterfaceの`I`をつける)もしくは単純に`Counter`で良いと思います！
https://github.com/pon0204/svelte-counter/blob/210b05f3737ec52cba4b57a996030aa9525abd19/src/types/types.ts#L1

**Comment by pon0204** [comment]
@KoichiKiyokawa 
ご指摘ありがとうございます!! 修正しました!!

【プルリクエストリンク】
https://github.com/pon0204/svelte-counter/pull/10

ご確認宜しくお願い致します。
