### ISSUE TITLE
イベントにすべてを集約しすぎている

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pon0204/svelte-counter#4]
https://github.com/pon0204/svelte-counter/blob/210b05f3737ec52cba4b57a996030aa9525abd19/src/App.svelte#L49

**Comment by KoichiKiyokawa** [comment]
`handleChangeCounter`というイベントにカウントのプラスマイナス、両方を担当させていますが、これは良くないです。
イベントを使うとしたら、`on:increment`, `on:decrement`のようにしたほうが良いです。

**Comment by KoichiKiyokawa** [comment]
一番良いのは以下のように`bind`をつかうことです。
svelteの良いところはたくさんありますが、このbindが最強だと個人的には思っています
```svelte
<Counter bind:count on:delete={...} />
```

**Comment by pon0204** [comment]
@KoichiKiyokawa 
> 一番いいのはbindを使うことです

なるほど!!  子コンポーネントの値をbindで参照出来るのですね!!
めちゃくちゃスマートになりました!🙏

【プルリクエストリンク】
https://github.com/pon0204/svelte-counter/pull/7

ご確認宜しくお願い致します。
