### ISSUE TITLE
末尾のカンマはとりたい

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pon0204/svelte-counter#6]
https://github.com/pon0204/svelte-counter/blob/210b05f3737ec52cba4b57a996030aa9525abd19/src/App.svelte#L55

![image](https://user-images.githubusercontent.com/40315079/134903639-e7f0981f-9934-4381-a112-887c244b6c83.png)

`new, new`と表示されるのが理想です

**Comment by pon0204** [comment]
@KoichiKiyokawa 
ご指摘ありがとうございます🙇‍♂️

こちらsliceメソッドで末尾のカンマを削除しました。

もし他にいい方法があればご教授お願い致します。

【プルリクエストリンク】
https://github.com/pon0204/svelte-counter/pull/11

ご確認宜しくお願い致します。
